#!/usr/bin/env python3
import argparse
import math
from pathlib import Path
from typing import List, Tuple

import numpy as np
import torch
from sklearn.preprocessing import StandardScaler


HEADER_PATH = Path("/home/utking/atracdencUltimate/src/atrac/at3/atrac3_ml_weights.h")
FEATURE_COLUMNS = ["band0", "band1", "band2", "band3", "transient", "flatness", "hf_ratio"]


def clamp_np(x: np.ndarray, lo: float = -1.0, hi: float = 1.0) -> np.ndarray:
    return np.clip(x, lo, hi)


def load_track_features(path: Path) -> np.ndarray:
    arr = np.genfromtxt(path, delimiter=",", names=True, dtype=np.float32)
    if arr.size == 0:
        raise ValueError(f"Empty feature CSV: {path}")

    if arr.ndim == 0:
        arr = np.array([arr], dtype=arr.dtype)

    missing = [c for c in FEATURE_COLUMNS if c not in arr.dtype.names]
    if missing:
        raise ValueError(f"Missing feature columns in {path}: {missing}")

    cols = [arr[c].astype(np.float32) for c in FEATURE_COLUMNS]
    return np.stack(cols, axis=1)


def load_delta_full(path: Path) -> float:
    if not path.exists():
        raise FileNotFoundError(f"Missing score file: {path}")
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line.startswith("delta_full"):
                continue
            if "=" not in line:
                continue
            _, value = line.split("=", 1)
            return float(value.strip())
    raise ValueError(f"delta_full not found in score file: {path}")


def discover_tracks(features_dir: Path) -> List[Tuple[str, Path]]:
    tracks: List[Tuple[str, Path]] = []
    for feat_path in sorted(features_dir.glob("*_features.csv")):
        name = feat_path.name
        slug = name[: -len("_features.csv")]
        if slug:
            tracks.append((slug, feat_path))
    return tracks


def synthetic_targets_from_raw(raw_x: np.ndarray, norm_x: np.ndarray) -> np.ndarray:
    transient = raw_x[:, 4]
    flatness = raw_x[:, 5]
    hf_ratio = raw_x[:, 6]

    transient_norm = norm_x[:, 4]
    hf_ratio_norm = norm_x[:, 6]

    bfu_bias_target = clamp_np(0.55 * hf_ratio_norm + 0.25 * transient_norm)
    tonal_bias_target = clamp_np(0.50 - flatness)
    gain_bias_target = clamp_np((transient - 4.5) * 0.22)
    hf_bias_target = clamp_np((hf_ratio - 0.24) * 4.0)

    return np.stack(
        [bfu_bias_target, tonal_bias_target, gain_bias_target, hf_bias_target], axis=1
    ).astype(np.float32)


def format_cpp_array(name: str, data: np.ndarray) -> str:
    flat = np.asarray(data, dtype=np.float32).reshape(-1)
    body = ", ".join(f"{float(v):.9g}f" for v in flat)
    return f"constexpr float {name}[{flat.size}] = {{{body}}};"


def export_header(path: Path, scaler: StandardScaler, model: torch.nn.Module) -> None:
    l1 = model.fc1
    l2 = model.fc2
    l3 = model.fc3

    if not all(isinstance(layer, torch.nn.Linear) for layer in (l1, l2, l3)):
        raise TypeError("Unexpected model architecture for export")

    mean = scaler.mean_.astype(np.float32)
    scale = scaler.scale_.astype(np.float32)

    w1 = l1.weight.detach().cpu().numpy().astype(np.float32)
    b1 = l1.bias.detach().cpu().numpy().astype(np.float32)
    w2 = l2.weight.detach().cpu().numpy().astype(np.float32)
    b2 = l2.bias.detach().cpu().numpy().astype(np.float32)
    w3 = l3.weight.detach().cpu().numpy().astype(np.float32)
    b3 = l3.bias.detach().cpu().numpy().astype(np.float32)

    lines = [
        "#pragma once",
        "",
        "// Auto-generated by tools/train_ml_alloc.py",
        "// Usage:",
        "// 1) Normalize input features x[i] with (x[i] - kMlScalerMean[i]) / kMlScalerStd[i]",
        "// 2) Run dense layers with ReLU after layer1 and layer2",
        "// 3) Apply tanh to 4 outputs: bfu_bias, tonal_bias, gain_bias, hf_noise_bias",
        "namespace NAtracDEnc {",
        "namespace NATRAC3ML {",
        "",
        format_cpp_array("kMlScalerMean", mean),
        format_cpp_array("kMlScalerStd", scale),
        "",
        "constexpr int kMlInputSize = 7;",
        "constexpr int kMlHidden1Size = 32;",
        "constexpr int kMlHidden2Size = 16;",
        "constexpr int kMlOutputSize = 4;",
        "",
        "// Row-major: out_neuron major, then input index.",
        format_cpp_array("kMlW1", w1),
        format_cpp_array("kMlB1", b1),
        format_cpp_array("kMlW2", w2),
        format_cpp_array("kMlB2", b2),
        format_cpp_array("kMlW3", w3),
        format_cpp_array("kMlB3", b3),
        "",
        "} // namespace NATRAC3ML",
        "} // namespace NAtracDEnc",
        "",
    ]

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


class TinyMlHintsNet(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.fc1 = torch.nn.Linear(7, 32)
        self.fc2 = torch.nn.Linear(32, 16)
        self.fc3 = torch.nn.Linear(16, 4)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = torch.tanh(self.fc3(x))
        return x


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Train tiny MLP for ATRAC3 ML hints and export C++ weights header"
    )
    parser.add_argument("--features-dir", required=True, type=Path)
    parser.add_argument("--scores-dir", required=True, type=Path)
    args = parser.parse_args()

    features_dir: Path = args.features_dir
    scores_dir: Path = args.scores_dir

    tracks = discover_tracks(features_dir)
    if not tracks:
        raise SystemExit(f"No *_features.csv files found in {features_dir}")

    x_parts: List[np.ndarray] = []
    y_parts: List[np.ndarray] = []

    for slug, feat_path in tracks:
        x_track = load_track_features(feat_path)
        delta_full = load_delta_full(scores_dir / f"score_{slug}.txt")
        y_track = np.full((x_track.shape[0],), delta_full, dtype=np.float32)

        x_parts.append(x_track)
        y_parts.append(y_track)

    x_raw = np.concatenate(x_parts, axis=0).astype(np.float32)
    y_delta = np.concatenate(y_parts, axis=0).astype(np.float32)

    scaler = StandardScaler()
    x_norm = scaler.fit_transform(x_raw).astype(np.float32)

    target = synthetic_targets_from_raw(x_raw, x_norm)

    x_tensor = torch.from_numpy(x_norm)
    t_tensor = torch.from_numpy(target)
    w_tensor = torch.from_numpy(np.exp(y_delta / 0.5).astype(np.float32)).unsqueeze(1)

    model = TinyMlHintsNet()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

    final_loss = math.nan
    for _ in range(200):
        optimizer.zero_grad(set_to_none=True)
        pred = model(x_tensor)
        mse = (pred - t_tensor) ** 2
        loss = (mse * w_tensor).mean()
        loss.backward()
        optimizer.step()
        final_loss = float(loss.detach().cpu().item())

    export_header(HEADER_PATH, scaler, model)

    print(f"num_tracks={len(tracks)}")
    print(f"num_frames={x_raw.shape[0]}")
    print(f"final_loss={final_loss:.8f}")


if __name__ == "__main__":
    main()
